[package]
name = "abe-benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.5.1"
rabe = "0.4.2"
#writing to csv
csv = "1.2"
anyhow = "1.0"
rand = "0.8"
bincode = "1.3"

[[bench]]
name = "criterion"
harness = false
